service: sls-s3-cf-react-website

# frameworkVersion: "=X.X.X"
custom:
    nm: "bananananananananana-5435434y653"
    dn: "bananananananananana-5435434y653.net"
    dnwww: www.${self:custom.dn}
    bn: ${self:custom.nm}-bucket-website


provider:
  name: aws
  runtime: nodejs8.10

#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

resources:
  - ${file(resources/buckets.yml)}
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
