service: sls-s3-cf-react-website

custom:
    nm: "ds-labs"
    dn: "ds-labs.xyz"
    dnwww: www.${self:custom.dn}
    bn: ${self:custom.nm}-bucket-website
    rbn: ${self:custom.bn}-redirect
    cfn: ${self:custom.nm}-website-cf
    rcfn: ${self:custom.cfn}-redirect
    certArn: "arn:aws:acm:us-east-1:061469306819:certificate/14109a34-9f8f-4144-be49-bd6eaf8b4344"
    dhzId: "Z20C7FJOX8RFEV"

provider:
  name: aws
  runtime: nodejs8.10

package:
  exclude:
    - website/**

resources:
  - ${file(resources/buckets.yml)}
  - ${file(resources/cloudfront-distributions.yml)}
  - ${file(resources/DNS-config.yml)}

Outputs:
  StaticWebsiteUploadCommand:
    Value:
      Fn::Join:
        - ""
        - - "aws s3 sync website/ s3://"
          - ${self:custom.bn}
          - " --delete && aws cloudfront create-invalidation --distribution-id "
          - Ref: RootCloudFront
          - " --paths '/*' && aws cloudfront create-invalidation --distribution-id "
          - Ref: RedirectCloudFront
          - " --paths '/*'"
