service: sls-s3-cf-react-website

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

resources:
  - ${file(resources/buckets.yml)}
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
