service: sls-s3-cf-react-website

# frameworkVersion: "=X.X.X"
custom:
    nm: "bananananananananana-5435434y653"
    dn: "bananananananananana-5435434y653.net"
    dnwww: www.${self:custom.dn}
    bn: ${self:custom.nm}-bucket-website
    rbn: ${self:custom.bn}-redirect
    cfn: ${self:custom.nm}-website-cf
    rcfn: ${self:custom.cfn}-redirect
    certArn: "arn:aws:acm:us-east-1:061469306819:certificate/14109a34-9f8f-4144-be49-bd6eaf8b4344"
    hzId: "Z20C7FJOX8RFEV"

provider:
  name: aws
  runtime: nodejs8.10

#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

resources:
  - ${file(resources/buckets.yml)}
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
