Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.bn}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:
              Fn::Join: ["", [Fn::GetAtt: [WebsiteBucket, Arn], "/*"] ]
      Bucket:
        Ref: WebsiteBucket
  RedirectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.rbn}
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: ${self:custom.dn}
            #Fn::GetAtt: [RootCloudFront, DomainName]
Outputs:
  WebsiteBucketName:
    Value:
      Ref: WebsiteBucket