Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "test43543543-5t436543y534y54"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
# Outputs:
#   WebsiteBucketName:
#     Value:
#       Ref: WebsiteBucket