Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.bn}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
Outputs:
  WebsiteBucketName:
    Value:
      Ref: WebsiteBucket